# electric_propulsion.py
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize_scalar


def thruster_performance(alpha, P_gen, eta, c):
    """
    Calculate the thrust and performance based on given parameters.
    """
    # Effective thrust for an electric propulsion system
    T = 2 * eta * P_gen / c
    # Measure of performance: Thrust-to-power ratio
    performance = T / alpha  # Maximizing T/m_plant = T / alpha
    return performance, T


def optimize_ep():
    """
    Optimize the Electric Propulsion (EP) system to maximize performance.
    """
    # System constants
    c = 50000  # Effective exhaust velocity (m/s), varies with Isp
    eta = 0.6  # Efficiency of thruster (60%)
    P_gen = 5000  # Power generated by the solar array (W)

    # Performance evaluation: Negative because we maximize
    def performance_function(alpha):
        performance, thrust = thruster_performance(alpha, P_gen, eta, c)
        return -performance  # Minimize negative performance to find the max

    # Optimize alpha (mass-to-power ratio): values range e.g., 1 to 20 kg/kW
    result = minimize_scalar(performance_function, bounds=(1, 20), method="bounded")

    # Extract the results
    optimal_alpha = result.x
    optimal_performance, optimal_thrust = thruster_performance(optimal_alpha, P_gen, eta, c)

    # Output results
    print(f"Optimal Mass-to-Power Ratio (Alpha): {optimal_alpha:.4f} kg/kW")
    print(f"Optimal Thrust: {optimal_thrust:.4f} N")
    print(f"Optimal Performance (T/m_plant): {optimal_performance:.6f} N/kg")

    # Plot performance curve for alpha
    alphas = np.linspace(1, 20, 100)
    performances = [-performance_function(a) for a in alphas]

    plt.plot(alphas, performances, label="Performance Curve")
    plt.scatter(optimal_alpha, optimal_performance, color="red", label="Optimal Alpha")
    plt.title("Electric Propulsion Optimization")
    plt.xlabel("Alpha (Mass-to-Power Ratio)")
    plt.ylabel("Performance (T/m)")
    plt.legend()
    plt.grid()
    plt.show()


if __name__ == "__main__":
    print("Running Electric Propulsion (EP) Optimization...\n")
    optimize_ep()